export { default as LogoElumTeam } from "./ElumTeam.svg"
export { default as Logo } from "./Logo.svg"

export { default as IconMessageEnd } from "./MessageEnd.svg"

export { default as IconArchiveFilled } from "./ArchiveFilled.svg"
export { default as IconMessageCircleFilled } from "./MessageCircleFilled.svg"
export { default as IconUserEdit } from "./UserEdit.svg"
export { default as IconMoodEdit } from "./MoodEdit.svg"
export { default as IconCameraPlus } from "./CameraPlus.svg"
export { default as IconCheck } from "./Check.svg"
export { default as IconChecks } from "./Checks.svg"
export { default as IconLetterCase } from "./LetterCase.svg"
export { default as IconPaperclip } from "./Paperclip.svg"
export { default as IconGiftFilled } from "./GiftFilled.svg"
export { default as IconCircleHalf } from "./CircleHalf.svg"
export { default as IconPhotoFilled } from "./PhotoFilled.svg"
export { default as IconDiamondFilled } from "./DiamondFilled.svg"
export { default as IconAlignBoxLeftTopFilled } from "./AlignBoxLeftTopFilled.svg"
export { default as IconBugFilled } from "./BugFilled.svg"
export { default as IconClose } from "./Close.svg"
export { default as IconSend } from "./Send.svg"
export { default as IconCopy } from "./Copy.svg"
export { default as IconEdit } from "./Edit.svg"
export { default as IconTrash } from "./Trash.svg"
export { default as IconShare3 } from "./Share3.svg"
export { default as IconX } from "./X.svg"
export { default as IconPlus } from "./Plus.svg"
export { default as IconAlert } from "./Alert.svg"
export { default as IconCarambolaFilled } from "./CarambolaFilled.svg"
export { default as IconFilterUp } from "./FilterUp.svg"
export { default as IconMessage2Search } from "./Message2Search.svg"
export { default as IconCoins } from "./Coins.svg"
export { default as IconBrush } from "./Brush.svg"
export { default as IconBookmarkPlus } from "./BookmarkPlus.svg"
export { default as IconLanguage } from "./Language.svg"
export { default as IconStack2Filled } from "./Stack2Filled.svg"
export { default as IconInvite } from "./Invite.svg" // в tabler icons называется по другому
export { default as IconMessageCircleCheck } from "./MessageCircleCheck.svg"
export { default as IconUsersGroup } from "./UsersGroup.svg"
export { default as IconUserPlus } from "./UserPlus.svg"
export { default as IconPhotoShare } from "./PhotoShare.svg"
export { default as IconAd } from "./Ad.svg"

export { default as IconTelegramStar } from "./TelegramStar.svg"
export { default as IconTON } from "./TON.svg"
